# Generated by Django 3.2.6 on 2021-10-06 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student', models.PositiveIntegerField()),
                ('Treacher', models.PositiveIntegerField()),
                ('studentenrollment', models.CharField(max_length=100)),
                ('studentdept', models.CharField(choices=[('Not Applicable', 'Not Applicable'), ('Mechanical', 'Mechanical'), ('Civil ', 'Civil '), ('Electrical', 'Electrical'), ('ComputerScience', 'Computer Science'), ('Electronics&Communication', 'Electronics & Communication')], default='Computer Science', max_length=40)),
                ('studentyear', models.CharField(choices=[('Not Applicable', 'Not Applicable'), ('FirstYear', 'First Year'), ('SecondYear ', 'Second Year '), ('ThirdYear', 'Third Year'), ('FourthYear', 'Fourth Year')], default='First Year', max_length=40)),
                ('studentsemester', models.CharField(choices=[('Not Applicable', 'Not Applicable'), ('FirstSemester', 'First Semester'), ('SecondSemester ', 'Second Semester '), ('ThirdSemester', 'Third Semester'), ('FourthSemester', 'Fourth Semester'), ('FifthSemester', 'Fifth Semester'), ('SixthSemester', 'Sixth Semester'), ('SeventhSemester', 'Seventh Semester'), ('EightthSemester', 'Eightth Semester')], default='First Semester', max_length=40)),
                ('subject', models.CharField(choices=[('Mathematics', 'Mathematics'), ('Data Structure & Algorithms', 'Data Structure & Algorithms'), ('Circuit Theory & Networks', 'Circuit Theory & Networks'), ('Computer Organisation', 'Computer Organisation'), ('Digital Electronics & Logic Design', 'Digital Electronics & Logic Design'), ('Principles of Programming Language', 'Principles of Programming Language'), ('Formal Language & Automata Theory', 'Formal Language & Automata Theory'), ('Operation Research & Optimization Techniques', 'Operation Research & Optimization Techniques'), ('Principles of Communication Engg', 'Principles of Communication Engg'), ('Advanced Computer Architecture', 'Advanced Computer Architecture'), ('Operating System', 'Operating System'), ('Database Management System', 'Database Management System'), ('Design & Analysis of Algorithm', 'Design & Analysis of Algorithm'), ('Microprocessor & Microcontrollers', 'Microprocessor & Microcontrollers'), ('Control System', 'Control System'), ('Computer network', 'Computer network'), ('Software Engineering', 'Software Engineering'), ('Computer Graphics & Multimedia', 'Computer Graphics & Multimedia'), ('System Software and Administration', 'System Software and Administration'), ('Object Technology & UML', 'Object Technology & UML'), ('Language \xa0Processor', 'Language \xa0Processor'), ('Artificial Intelligence', 'Artificial Intelligence'), ('Visual Programming and Web technology', 'Visual Programming and Web technology'), ('Financial Management and accounts', 'Financial Management and accounts')], default='Mathematics', max_length=80)),
                ('total_attendence', models.IntegerField(default=0)),
                ('total_class', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('total_makrs', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(choices=[('Not Applicable', 'Not Applicable'), ('Mechanical', 'Mechanical'), ('Civil ', 'Civil '), ('Electrical', 'Electrical'), ('ComputerScience', 'Computer Science'), ('Electronics&Communication', 'Electronics & Communication')], default='Computer Science', max_length=40)),
                ('year', models.CharField(choices=[('Not Applicable', 'Not Applicable'), ('FirstYear', 'First Year'), ('SecondYear ', 'Second Year '), ('ThirdYear', 'Third Year'), ('FourthYear', 'Fourth Year')], default='First Year', max_length=40)),
                ('semester', models.CharField(choices=[('Not Applicable', 'Not Applicable'), ('FirstSemester', 'First Semester'), ('SecondSemester ', 'Second Semester '), ('ThirdSemester', 'Third Semester'), ('FourthSemester', 'Fourth Semester'), ('FifthSemester', 'Fifth Semester'), ('SixthSemester', 'Sixth Semester'), ('SeventhSemester', 'Seventh Semester'), ('EightthSemester', 'Eightth Semester')], default='First Semester', max_length=40)),
                ('enrollment', models.CharField(blank=True, max_length=70, null=True)),
                ('conactno', models.IntegerField(blank=True, max_length=15, null=True)),
                ('profilepic', models.ImageField(blank=True, null=True, upload_to='profile_pic/')),
                ('startdate', models.DateField(auto_now=True)),
                ('enddate', models.DateField(auto_now=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityname', models.CharField(max_length=70)),
                ('activitydetails', models.TextField(max_length=500)),
                ('activityimage', models.ImageField(blank=True, null=True, upload_to='Activity/')),
                ('activitydate', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('activityowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
