# Generated by Django 3.2.6 on 2021-10-07 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0005_auto_20211007_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='yearbatch',
            field=models.CharField(choices=[('', 'Batch'), ('2014-18', '2014-18'), ('2015-19', '2015-19'), ('2016-20', '2016-20'), ('2017-21', '2017-21'), ('2018-22', '2018-22'), ('2019-23', '2019-23')], default='2019-23', max_length=40),
        ),
    ]
