# Generated by Django 3.2.6 on 2021-10-07 07:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0006_user_yearbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='education',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='regno',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
