# Generated by Django 3.2.6 on 2021-10-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0007_auto_20211007_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='project',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='skill',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='education',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
