# Generated by Django 3.2.6 on 2021-10-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0009_auto_20211007_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic',
            name='studentdept',
            field=models.CharField(choices=[('', 'Depertment'), ('Not Applicable', 'Not Applicable'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('ComputerScience Engineering', 'Computer Science Engineering'), ('Electronics & Communication Engineering', 'Electronics & Communication Engineering')], default='Computer Science', max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='dept',
            field=models.CharField(choices=[('', 'Depertment'), ('Not Applicable', 'Not Applicable'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Electrical Engineering', 'Electrical Engineering'), ('ComputerScience Engineering', 'Computer Science Engineering'), ('Electronics & Communication Engineering', 'Electronics & Communication Engineering')], default='Computer Science', max_length=40),
        ),
    ]
