# Generated by Django 3.2.6 on 2021-10-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0010_auto_20211007_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic',
            name='studentsemester',
            field=models.CharField(choices=[('', 'Semester'), ('Not Applicable', 'Not Applicable'), ('1st Semester', 'First Semester'), ('2nd Semester', 'Second Semester '), ('3rd Semester', 'Third Semester'), ('4th Semester', 'Fourth Semester'), ('5th Semester', 'Fifth Semester'), ('6th Semester', 'Sixth Semester'), ('7th Semester', 'Seventh Semester'), ('8th Semester', 'Eightth Semester')], default='First Semester', max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='semester',
            field=models.CharField(choices=[('', 'Semester'), ('Not Applicable', 'Not Applicable'), ('1st Semester', 'First Semester'), ('2nd Semester', 'Second Semester '), ('3rd Semester', 'Third Semester'), ('4th Semester', 'Fourth Semester'), ('5th Semester', 'Fifth Semester'), ('6th Semester', 'Sixth Semester'), ('7th Semester', 'Seventh Semester'), ('8th Semester', 'Eightth Semester')], default='First Semester', max_length=40),
        ),
    ]
