# Generated by Django 3.2.6 on 2021-10-07 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0011_auto_20211007_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='active',
            new_name='status',
        ),
    ]
