# Generated by Django 3.2.6 on 2021-10-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0012_rename_active_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jyear',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
