# Generated by Django 3.2.6 on 2021-10-08 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0013_user_jyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic',
            name='subjectattendence',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='academic',
            name='subjectclass',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='academic',
            name='subjectmarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='academic',
            name='subjectscore',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
