# Generated by Django 3.2.6 on 2021-10-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0014_auto_20211008_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic',
            name='Student',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academic',
            name='Treacher',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
