# Generated by Django 3.2.6 on 2021-10-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0015_auto_20211008_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic',
            name='studentyear',
            field=models.CharField(choices=[('', 'Year'), ('Not Applicable', 'Not Applicable'), ('First Year', 'First Year'), ('Second Year', 'Second Year '), ('Third Year', 'Third Year'), ('Fourth Year', 'Fourth Year')], default='First Year', max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='skill',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='year',
            field=models.CharField(choices=[('', 'Year'), ('Not Applicable', 'Not Applicable'), ('First Year', 'First Year'), ('Second Year', 'Second Year '), ('Third Year', 'Third Year'), ('Fourth Year', 'Fourth Year')], default='First Year', max_length=40),
        ),
    ]
