# Generated by Django 3.2.6 on 2021-10-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0016_auto_20211009_0058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Massage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peopleemail', models.EmailField(blank=True, max_length=254)),
                ('sms', models.TextField(blank=True, max_length=200)),
            ],
        ),
    ]
