# Generated by Django 3.2.6 on 2021-10-09 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsite', '0018_rename_sms_massage_massage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='massage',
            old_name='peopleemail',
            new_name='email',
        ),
    ]
